---
- name: Download Grafana archive
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana-8.2.5.linux-amd64.tar.gz"
    dest: "/tmp/grafana.tar.gz"
  notify:
    - verify grafana
    - report grafana

- name: Extract Grafana archive
  ansible.builtin.unarchive:
    src: "/tmp/grafana.tar.gz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/grafana-8.2.5"

- name: Create symbolic link for Grafana
  ansible.builtin.file:
    src: "/opt/grafana-8.2.5"
    dest: "/opt/grafana"
    state: link
    force: yes

- name: Set ownership and permissions for Grafana directory
  ansible.builtin.file:
    path: "/opt/grafana"
    owner: root
    group: sudo
    mode: "0755"