---
- name: Update package cache
  apt:
    update_cache: yes

- name: Install OpenJDK 11
  apt:
    name: openjdk-17-jdk
    state: present

- name: Set the JAVA_HOME in /etc/environment file
  lineinfile:
    path: /etc/environment
    state: present
    line: 'JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"'

- name: Reload /etc/profile file
  ansible.builtin.shell: source /etc/profile
  args:
    executable: /bin/bash
