---
- name: install mysql
  apt:
    name:
      - mysql-client
      - mysql-server
    state: latest
    update_cache: yes
  notify:
    - start mysql

- name: Make sure pymysql is present
  apt:
    name: python3-mysqldb
    state: latest
