---
- name: Install Prometheus
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"
  notify:
    - verify prometheus
    - report prometheus

- name: Extract Prometheus archive
  ansible.builtin.unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/prometheus"

- name: Create symbolic link for Prometheus
  ansible.builtin.file:
    src: "/opt/prometheus-2.30.3.linux-amd64"
    dest: "/opt/prometheus"
    state: link
    force: yes

- name: Set ownership and permissions for Prometheus directory
  ansible.builtin.file:
    path: "/opt/prometheus"
    owner: root
    group: sudo
    mode: "0755"